{
 "title": "Artec Service",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "description": "Total de pods rodando.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\", pod=~\"Artec-service.*\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "description": "Total de pods pendentes.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\", pod=~\"Artec-service.*\"})"
    }
   ]
  },
  {
   "title": "Pods Unavailable",
   "type": "stat",
   "description": "Total de pods inativos.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\", pod=~\"Artec-service.*\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "description": "Total de pods.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\", pod=~\"Artec-service.*\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\", pod=~\"Artec-service.*\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\", pod=~\"Artec-service.*\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU of Requests",
     "type": "gauge",
     "description": "CPU of Requests",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg(kube_pod_container_resource_requests{container=\"Artec-service\", resource=\"cpu\"}) - avg(rate(container_cpu_usage_seconds_total{container=\"Artec-service\", image!=\"\"}[5m]))) * 100",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Memory of Requests",
     "type": "gauge",
     "description": "Memory of Requests",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg(container_memory_working_set_bytes{container=\"Artec-service\", image!=\"\"}) / avg(kube_pod_container_resource_requests{resource=\"memory\", container=\"Artec-service\"})) * 100",
       "legendFormat": "Usage"
      }
     ]
    }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Message count",
   "type": "timeseries",
   "description": "O número produzido é a soma total de mensagens prontas e não confirmadas no broker.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Queue": "Artec:RENEW_SUBSCRIPTION" },
     "metricName": "MessageCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Queue": "NOTIFICATION:SEND_Artec" },
     "metricName": "MessageCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Consumers count",
   "type": "timeseries",
   "description": "O número produzido é a soma total de consumidores por fila.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Queue": "Artec:RENEW_SUBSCRIPTION" },
     "metricName": "ConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Queue": "NOTIFICATION:SEND_Artec" },
     "metricName": "ConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "Artec-production" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}