{
 "title": "Amazon MQ [RabbitMQ engine] - Cloudwatch",
 "description": "Visualize Amazon MQ (RabbitMQ) metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "broker",
    "label": "Broker",
    "query": "dimension_values($region,AWS/AmazonMQ, SystemCpuUtilization, Broker)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "dimension_values($region, AWS/AmazonMQ, SystemCpuUtilization, Node, {\"Broker\":\"$broker\"})"
   },
   {
    "name": "virtualhost",
    "label": "Virtual Host",
    "query": "dimension_values($region,AWS/AmazonMQ, ConsumerCount, VirtualHost, {\"Broker\":\"$broker\"})"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "dimension_values($region,AWS/AmazonMQ, ConsumerCount, Queue, {\"Broker\":\"$broker\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregated Broker level Metrics [by Broker]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exchange count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"ExchangeCount\" \"Broker\"=\"$broker\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Queue count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"QueueCount\" \"Broker\"=\"$broker\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"ConnectionCount\" \"Broker\"=\"$broker\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Channel count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"ChannelCount\" \"Broker\"=\"$broker\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Publish Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"PublishRate\" \"Broker\"=\"$broker\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Confirm Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"ConfirmRate\" \"Broker\"=\"$broker\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Ack Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"AckRate\" \"Broker\"=\"$broker\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Consumer count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"ConsumerCount\" \"Broker\"=\"$broker\" \"Queue\" ', 'Average', 300)))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Message count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageCount\" \"Broker\"=\"$broker\" \"Queue\" ', 'Average', 300)))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Message Ready count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageReadyCount\" \"Broker\"=\"$broker\" \"Queue\" ', 'Average', 300)))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Message Unacknowledged count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageUnacknowledgedCount\" \"Broker\"=\"$broker\" \"Queue\" ', 'Average', 300)))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Individual Queue Metrics [by Broker, Virtual host and Queue]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$queue",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageCount\" \"Broker\"=\"$broker\" \"VirtualHost\"=\"$virtualhost\" \"Queue\"=\"$queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageReadyCount\" \"Broker\"=\"$broker\" Queue=\"$queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageUnacknowledgedCount\" \"Broker\"=\"$broker\" Queue=\"$queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"ConsumerCount\" \"Broker\"=\"$broker\" Queue=\"$queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "All Queues Metrics [by Broker, Virtual host and Queue]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Message count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageCount\" \"Broker\"=\"$broker\" \"VirtualHost\"=\"$virtualhost\" \"Queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Consumer count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"ConsumerCount\" \"Broker\"=\"$broker\" \"VirtualHost\"=\"$virtualhost\" \"Queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Message Ready  count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageReadyCount\" \"Broker\"=\"$broker\" \"VirtualHost\"=\"$virtualhost\" \"Queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Message Unacknowledged Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "TargetGroup": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"MessageUnacknowledgedCount\" \"Broker\"=\"$broker\" \"VirtualHost\"=\"$virtualhost\" \"Queue\" ', 'Average', 300))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "HealthyHostCount",
       "namespace": "AWS/AmazonMQ",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Node / Instance Metrics [by Broker]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "\tREMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"SystemCpuUtilization\" \"Broker\"=\"$broker\" Node=\"$node\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "File descriptors used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "\tREMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"RabbitMQFdUsed\" \"Broker\"=\"$broker\" Node=\"$node\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "\tREMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"RabbitMQMemLimit\" \"Broker\"=\"$broker\" Node=\"$node\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "\tREMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"RabbitMQMemUsed\" \"Broker\"=\"$broker\" Node=\"$node\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Free Limit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "\tREMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"RabbitMQDiskFreeLimit\" \"Broker\"=\"$broker\" Node=\"$node\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "application": { "filter": "" },
     "dimensions": { "TargetGroup": "*" },
     "expression": "\tREMOVE_EMPTY(SEARCH('Namespace=\"AWS/AmazonMQ\" MetricName=\"RabbitMQDiskFree\" \"Broker\"=\"$broker\" Node=\"$node\" ', 'Average', 300))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "HealthyHostCount",
     "namespace": "AWS/AmazonMQ",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}