{
 "title": "Onboard Service",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "description": "Total de pods rodando.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\", pod=~\"onboard-service.*\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "description": "Total de pods pendentes.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\", pod=~\"onboard-service.*\"})"
    }
   ]
  },
  {
   "title": "Pods Unavailable",
   "type": "stat",
   "description": "Total de pods inativos.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\", pod=~\"onboard-service.*\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "description": "Total de pods.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\", pod=~\"onboard-service.*\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\", pod=~\"onboard-service.*\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\", pod=~\"onboard-service.*\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conexões Ativas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(onboard:nodejs_active_requests)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU of Requests",
   "type": "gauge",
   "description": "CPU of Requests",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{container=\"onboard-service\", resource=\"cpu\"}) - avg(rate(container_cpu_usage_seconds_total{container=\"onboard-service\", image!=\"\"}[5m]))) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory of Requests",
   "type": "gauge",
   "description": "Memory of Requests",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(container_memory_working_set_bytes{container=\"onboard-service\", image!=\"\"}) / avg(kube_pod_container_resource_requests{resource=\"memory\", container=\"onboard-service\"})) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "Artec-onboard-production" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "Artec-onboard-production" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "Artec-onboard-production" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Message count",
   "type": "timeseries",
   "description": "O número produzido é a soma total de mensagens prontas e não confirmadas no broker.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Queue": "ONBOARD:REGISTER_CLIENT_STATUS" },
     "metricName": "MessageCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Queue": "ONBOARD:SEND_DOCUMENTS" },
     "metricName": "MessageCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "Queue": "ONBOARD:UPDATE_DOCUMENTS_STATUS"
     },
     "metricName": "MessageCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Consumers count",
   "type": "timeseries",
   "description": "O número produzido é a soma total de consumidores por fila.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Queue": "ONBOARD:REGISTER_CLIENT_STATUS" },
     "metricName": "ConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Queue": "ONBOARD:SEND_DOCUMENTS" },
     "metricName": "ConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "Queue": "ONBOARD:UPDATE_DOCUMENTS_STATUS"
     },
     "metricName": "ConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}