{
 "title": "Services",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Service", "query": { "query": "label_values(deployment)" } }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "description": "Total de pods rodando.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\", pod=~\"$Service.*\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "description": "Total de pods pendentes.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\", pod=~\"$Service.*\"})"
    }
   ]
  },
  {
   "title": "Pods Unavailable",
   "type": "stat",
   "description": "Total de pods inativos.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\", pod=~\"$Service.*\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "description": "Total de pods.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\", pod=~\"$Service.*\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\", pod=~\"$Service.*\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\", pod=~\"$Service.*\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU of Requests",
   "type": "gauge",
   "description": "CPU of Requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{container=\"$Service\", resource=\"cpu\"}) - avg(rate(container_cpu_usage_seconds_total{container=\"$Service\", image!=\"\"}[5m]))) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory of Requests",
   "type": "gauge",
   "description": "Memory of Requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(container_memory_working_set_bytes{container=\"$Service\", image!=\"\"}) / avg(kube_pod_container_resource_requests{resource=\"memory\", container=\"$Service\"})) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Limits/Request/Usage",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"$Service\", image!=\"\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{container=\"$Service\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{container=\"$Service\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Limits/Request/Usage",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{container=\"$Service\", image!=\"\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", container=\"$Service\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", container=\"$Service\"})",
     "legendFormat": "Request"
    }
   ]
  }
 ]
}